Update hacktoberfest.md
MicrosoftDocs/Contribute pull request #844
Opened 2023-09-26 19:52 UTC by IEvangelist

# Contributor guide pull request

Thanks for contributing to the [Microsoft Learn contributor guide](https://learn.microsoft.com/contribute/?branch=main). Please read these instructions for processing your pull request (PR). Once you've read this text, delete it and write a brief description of the changes you're proposing.

## Quality control

- [ ] 1. **Successful build with no warnings**: Review the build status to make sure **all checks are green** (Succeeded).

- [ ] 2. **#Sign-off**: Once the PR is finalized and ready to be merged, indicate so by typing `#sign-off` in a new comment in the PR. Signing off means the document is ready for review and can be published at any time.

## Merge and publish

- All PRs to this repository are manually reviewed and merged.
- Once all feedback on the PR is addressed, we'll merge the PR into the main branch.

## Need help?

- If you have an open PR, tag the PR reviewers in comment with your question: `@carlyrevier, @jehchow`
- Open an issue in this repo and tag the PR reviewers.

2023-09-26 20:00 UTC, IEvangelist commented
#sign-off

2023-09-26 20:42 UTC, jehchow reviewed
@IEvangelist Just a few minor corrections to make. Thanks!

2023-09-26 20:42 UTC, jehchow commented on Contribute/content/hacktoberfest.md
> +> If your a repo Admin and you want to allow your repo to participate in Hacktoberfest, add the `hacktoberfest` topic to the repo. For more information, see [Classifying your repository with topics](
```suggestion
> If you're a repo admin and you want to allow your repo to participate in Hacktoberfest, add the `hacktoberfest` topic to the repo. For more information, see [Classifying your repository with topics](https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics).
```

2023-09-26 22:53 UTC, carlyrevier requested changes
Hi @IEvangelist - I changed one typo and left a comment about a bracketed statement that looks like it's supposed to be a link.

2023-09-26 22:53 UTC, carlyrevier commented on Contribute/content/hacktoberfest.md
> +To contribute to an open source repo, you must first configure your account to contribute to Microsoft Learn. If you have never completed this process, start by [signing up for a GitHub account](./ge
```suggestion
To contribute to an open source repo, you must first configure your account to contribute to Microsoft Learn. If you have never completed this process, start by [signing up for a GitHub account](./get-started-setup-github.md). You must also register a profile to track your efforts. See [Hacktoberfest](https://hacktoberfest.com/).
```

2023-09-26 22:53 UTC, carlyrevier commented on Contribute/content/hacktoberfest.md
> +For more information, see [Hacktoberfest: Participation].
Did you mean to make this a link?

2023-09-27 01:14 UTC, IEvangelist commented on Contribute/content/hacktoberfest.md
> +For more information, see [Hacktoberfest: Participation].
```suggestion
For more information, see [Hacktoberfest: Participation](https://hacktoberfest.com/participation).
```

2023-09-27 01:15 UTC, IEvangelist commented
#sign-off

2023-09-27 21:31 UTC, carlyrevier approved these changes

2023-09-27 21:31 UTC, merged